[package]
name = "gx"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gx"
path = "src/main.rs"

[lib]
name = "gx"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5.43", features = ["derive"] }
colored = "3.0.0"
dirs = "6.0.0"
env_logger = "0.11.8"
eyre = "0.6.12"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
rayon = "1.8"
walkdir = "2.4"
url = "2.5"
tempfile = "3.8"
# Using std::process::Command for git calls like slam

[dev-dependencies]

[build-dependencies]
# For build.rs if needed
