[package]
name = "gx"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "gx"
path = "src/main.rs"

[lib]
name = "gx"
path = "src/lib.rs"

[dependencies]
chrono = { version = "0.4.42", features = ["clock"] }
clap = { version = "4.5.47", features = ["derive"] }
colored = "3.0.0"
dirs = "6.0.0"
env_logger = "0.11.8"
eyre = "0.6.12"
glob = "0.3.3"
log = "0.4.28"
num_cpus = "1.17"
rayon = "1.11"
regex = "1.11.2"
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.34"
similar = "2.7.0"
tempfile = "3.22"
string-width = "0.1"
walkdir = "2.5"
# Using std::process::Command for git calls like slam

[dev-dependencies]

[build-dependencies]
# For build.rs if needed
